#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = []
# ///
# ruff: noqa: EXE001 (module is 0644 by design; imported, never run directly)
"""Shared runtime helpers for generated project-kit scripts. Generated by project-kit."""

from __future__ import annotations

import json
import socket
import subprocess
import sys
import urllib.request
from datetime import UTC, datetime

_events: list[dict[str, object]] = []


def log(level: str, msg: str, **context: object) -> dict[str, object]:
    """Build one structured event, buffer it, and print compact JSON to stderr."""
    event: dict[str, object] = {
        "level": level,
        "msg": msg,
        "time": datetime.now(UTC).isoformat(),
        **context,
    }
    _events.append(event)
    print(json.dumps(event, separators=(",", ":")), file=sys.stderr)
    return event


def flush_events(loki_url: str, job: str, script: str, host: str) -> bool:
    """Post buffered events to the Loki push API as one stream, best effort.

    Returns True on success and False on any failure; never raises.
    """
    try:
        values = [
            [
                str(int(datetime.fromisoformat(str(event["time"])).timestamp() * 1_000_000_000)),
                json.dumps(event),
            ]
            for event in _events
        ]
        payload = {
            "streams": [
                {
                    "stream": {"job": job, "script": script, "host": host},
                    "values": values,
                }
            ]
        }
        request = urllib.request.Request(
            loki_url,
            data=json.dumps(payload).encode(),
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(request, timeout=3):
            pass
    except Exception:  # noqa: BLE001 - logging must never block deployment
        return False
    _events.clear()
    return True


def execution_host() -> str:
    """Short lowercase host label for the machine running this script."""
    return socket.gethostname().split(".", 1)[0].lower()


def run(
    cmd: list[str],
    *,
    timeout: float | None = None,
    cwd: str | None = None,
    capture: bool = False,
) -> subprocess.CompletedProcess:
    """Thin subprocess.run wrapper; capture=True implies capture_output and text."""
    return subprocess.run(
        cmd, timeout=timeout, cwd=cwd, capture_output=capture, text=capture, check=False
    )
