#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = [
#   "typer>=0.12",
# ]
# ///
"""Read-only delivery status and plan for personal-site.

Generated by project-kit. Every command inspects Git, GitHub, and configured
delivery state without writing or mutating files.

Plan steps report one of five states: ``done``, ``pending``,
``not_configured``, ``unknown`` (indeterminate tool or network state), and
``unsupported`` (a production check against a deploy target without status
support, which exits 0).
"""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

import typer

LOCKFILE = ".project-kit/answers.lock.json"
MAX_OUTPUT_CHARS = 4000
SUBPROCESS_TIMEOUT_SECONDS = 20
app = typer.Typer(add_completion=False)


def _run(
    command: list[str],
    *,
    cwd: Path,
    timeout: float = SUBPROCESS_TIMEOUT_SECONDS,
) -> subprocess.CompletedProcess[str] | None:
    try:
        return subprocess.run(
            command,
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
            start_new_session=True,
        )
    except (FileNotFoundError, PermissionError, subprocess.TimeoutExpired):
        return None


def _config(repo: Path) -> dict[str, object]:
    try:
        payload = json.loads((repo / LOCKFILE).read_text())
    except (FileNotFoundError, OSError, json.JSONDecodeError):
        return {}
    return payload if isinstance(payload, dict) else {}


def _section(config: dict[str, object], name: str) -> dict[str, object]:
    value = config.get(name)
    return value if isinstance(value, dict) else {}


def _branch(repo: Path) -> str:
    result = _run(["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd=repo)
    branch = result.stdout.strip() if result is not None and result.returncode == 0 else ""
    return branch if branch not in ("", "HEAD") else "detached"


def _head(repo: Path) -> str | None:
    result = _run(["git", "rev-parse", "HEAD"], cwd=repo)
    value = result.stdout.strip() if result is not None and result.returncode == 0 else ""
    return value or None


def _dirty_count(repo: Path) -> int | None:
    result = _run(["git", "status", "--porcelain"], cwd=repo)
    if result is None or result.returncode != 0:
        return None
    return len(result.stdout.splitlines())


def _upstream(repo: Path) -> dict[str, int | None] | None:
    result = _run(
        ["git", "rev-list", "--left-right", "--count", "@{upstream}...HEAD"],
        cwd=repo,
    )
    if result is None or result.returncode != 0:
        return None
    parts = result.stdout.strip().split()
    if len(parts) != 2:
        return None
    try:
        behind, ahead = (int(part) for part in parts)
    except ValueError:
        return None
    return {"ahead": ahead, "behind": behind}


def _latest_tag(repo: Path) -> str | None:
    result = _run(
        ["git", "describe", "--tags", "--abbrev=0", "--match=v*"],
        cwd=repo,
    )
    value = result.stdout.strip() if result is not None and result.returncode == 0 else ""
    return value or None


def _tag_target(repo: Path, tag: str) -> str | None:
    result = _run(["git", "rev-list", "-n", "1", tag], cwd=repo)
    if result is None or result.returncode != 0:
        return None
    return result.stdout.strip() or None


def _json_output(result: subprocess.CompletedProcess[str] | None) -> dict[str, object] | None:
    if result is None or result.returncode != 0:
        return None
    try:
        payload = json.loads(result.stdout)
    except json.JSONDecodeError:
        return None
    return payload if isinstance(payload, dict) else None


def _pull_request(repo: Path, branch: str) -> object:
    if not shutil.which("gh") or branch == "detached":
        return "unavailable"
    payload = _json_output(
        _run(["gh", "pr", "view", branch, "--json", "number,url,state,mergeCommit"], cwd=repo),
    )
    return payload if payload is not None else "unavailable"


def _github_release(repo: Path, tag: str | None) -> object:
    if not shutil.which("gh") or not tag:
        return "unavailable"
    payload = _json_output(
        _run(["gh", "release", "view", tag, "--json", "isDraft,url,state"], cwd=repo),
    )
    return payload if payload is not None else "unavailable"


def _images(config: dict[str, object]) -> list[dict[str, str]]:
    build = _section(config, "build")
    values = build.get("images", [])
    if not isinstance(values, list):
        return []
    images: list[dict[str, str]] = []
    for value in values:
        if not isinstance(value, dict):
            continue
        name = value.get("name")
        registry = value.get("registry")
        if isinstance(name, str) and isinstance(registry, str) and name and registry:
            images.append({"name": name, "registry": registry})
    return images


def _digests(repo: Path, images: list[dict[str, str]], tag: str | None) -> list[dict[str, str]]:
    if not tag:
        return [
            {"name": image["name"], "registry": image["registry"], "digest": "unknown"}
            for image in images
        ]
    result = []
    for image in images:
        reference = f"{image['registry']}/{image['name']}:{tag}"
        digest = "unknown"
        if shutil.which("crane"):
            result_result = _run(["crane", "digest", reference], cwd=repo)
            if (
                result_result is not None
                and result_result.returncode == 0
                and result_result.stdout.strip()
            ):
                digest = result_result.stdout.strip()
        elif shutil.which("docker"):
            result_result = _run(
                ["docker", "manifest", "inspect", "-v", reference],
                cwd=repo,
            )
            if result_result is not None and result_result.returncode == 0:
                try:
                    payload = json.loads(result_result.stdout)
                except json.JSONDecodeError:
                    payload = None
                if isinstance(payload, dict):
                    digest_value = payload.get("Descriptor", {}).get("digest")
                    if isinstance(digest_value, str) and digest_value:
                        digest = digest_value
                elif isinstance(payload, list) and payload:
                    first = payload[0]
                    if isinstance(first, dict):
                        digest_value = first.get("Descriptor", {}).get("digest")
                        if isinstance(digest_value, str) and digest_value:
                            digest = digest_value
        result.append(
            {
                "name": image["name"],
                "registry": image["registry"],
                "digest": digest,
            }
        )
    return result


def _deploy_config(config: dict[str, object]) -> dict[str, str | None]:
    deploy = _section(config, "deploy")
    target = deploy.get("target")
    host = deploy.get("host")
    if not isinstance(target, str) or not target:
        target = "none"
    if not isinstance(host, str) or not host:
        host = None
    return {"target": target, "host": host}


def _deploy_enabled(config: dict[str, object]) -> bool:
    deploy = _section(config, "deploy")
    return (
        bool(deploy.get("enabled"))
        and bool(deploy.get("target"))
        and deploy.get("target") != "none"
    )


def _deploy_script(repo: Path, target: str) -> Path:
    return repo / ".project-kit" / "scripts" / f"deploy-{target}.py"


def _production_deploy_check(
    repo: Path,
    config: dict[str, object],
) -> dict[str, object] | None:
    deploy = _deploy_config(config)
    target = deploy["target"]
    if target is None or target == "none":
        return None
    script = _deploy_script(repo, target)
    if not script.is_file():
        return {"exit_status": None, "output_tail": "unavailable"}
    result = _run(["uv", "run", str(script), "--status"], cwd=repo, timeout=60)
    if result is None:
        return {"exit_status": None, "output_tail": "unavailable"}
    output = f"{result.stdout}{result.stderr}".strip()
    return {
        "exit_status": result.returncode,
        "output_tail": output[-MAX_OUTPUT_CHARS:] if output else "",
        "supported": "do not support" not in output,
    }


def _local_tag_exists(repo: Path, tag: str) -> bool:
    result = _run(
        ["git", "show-ref", "--verify", "--quiet", f"refs/tags/{tag}"],
        cwd=repo,
    )
    return result is not None and result.returncode == 0


def _remote_tag_exists(repo: Path, tag: str) -> bool | None:
    result = _run(
        ["git", "ls-remote", "--exit-code", "origin", f"refs/tags/{tag}"],
        cwd=repo,
    )
    if result is None:
        return None
    if result.returncode == 2:
        return False
    if result.returncode != 0:
        return None
    return bool(result.stdout.strip())


def _release_enabled(config: dict[str, object]) -> bool:
    return bool(_section(config, "release").get("enabled"))


def _build_enabled(config: dict[str, object]) -> bool:
    build = _section(config, "build")
    return bool(build.get("enabled")) and bool(build.get("image_enabled"))


def _status_payload(repo: Path, production: bool) -> dict[str, object]:
    config = _config(repo)
    branch = _branch(repo)
    head = _head(repo)
    latest_tag = _latest_tag(repo)
    tag_target = _tag_target(repo, latest_tag) if latest_tag else None
    dirty_files = _dirty_count(repo)
    upstream = _upstream(repo)
    images = _images(config)
    image_tag = latest_tag or head
    payload: dict[str, object] = {
        "branch": branch,
        "dirty_files": dirty_files,
        "upstream": (
            upstream
            if upstream is not None
            else {
                "ahead": None,
                "behind": None,
            }
        ),
        "pull_request": _pull_request(repo, branch),
        "release": {
            "latest_tag": latest_tag,
            "tag_targets_head": bool(tag_target and head and tag_target == head),
            "github_release": _github_release(repo, latest_tag),
        },
        "build": {"images": _digests(repo, images, image_tag)},
        "deploy": _deploy_config(config),
    }
    if production:
        payload["deploy"]["status_check"] = _production_deploy_check(repo, config)
    return payload


def _plan_states(
    repo: Path,
    tag: str,
    config: dict[str, object],
    production: bool,
) -> list[dict[str, str]]:
    status = _status_payload(repo, production=False)
    remote_tag = _remote_tag_exists(repo, tag)
    upstream = status["upstream"]
    release = status["release"]
    assert isinstance(upstream, dict)
    assert isinstance(release, dict)
    pull_request = status["pull_request"]
    tag_state = "unknown" if remote_tag is None else "pending"
    if _local_tag_exists(repo, tag) and remote_tag is True:
        tag_state = "done"

    image_state = "not_configured"
    if _build_enabled(config):
        if not status["build"]["images"]:
            image_state = "not_configured"
        elif shutil.which("crane") is None and shutil.which("docker") is None:
            image_state = "unknown"
        elif all(image["digest"] != "unknown" for image in status["build"]["images"]):
            image_state = "done"
        else:
            image_state = "pending"

    deployed = None
    if production:
        if not _deploy_enabled(config):
            deployed = "not_configured"
        else:
            check = _production_deploy_check(repo, config)
            if check is None or check["exit_status"] is None:
                deployed = "unknown"
            elif check.get("supported") and check["exit_status"] == 0:
                deployed = "done"
            elif not check.get("supported"):
                deployed = "unsupported"
            else:
                deployed = "pending"

    if isinstance(pull_request, dict):
        pr_state = (
            "done"
            if (pull_request.get("state") == "MERGED" or pull_request.get("mergeCommit"))
            else "pending"
        )
    else:
        pr_state = "unknown"

    github_release = release.get("github_release")
    if not _release_enabled(config):
        release_state = "not_configured"
    elif isinstance(github_release, dict) and github_release.get("isDraft") is False:
        release_state = "done"
    elif github_release == "unavailable":
        release_state = "unknown"
    else:
        release_state = "pending"

    dirty = status["dirty_files"]
    steps = [
        {"step": "clean_tree", "state": "done" if dirty == 0 else "pending"},
        {
            "step": "branch_published",
            "state": "done" if upstream.get("ahead") == 0 else "pending",
        },
        {"step": "pr_merged", "state": pr_state},
        {"step": "tag_published", "state": tag_state},
        {"step": "release_published", "state": release_state},
        {"step": "image_built", "state": image_state},
    ]
    if production:
        steps.append({"step": "deployed", "state": deployed or "unknown"})
    return steps


def _print_status(payload: dict[str, object]) -> None:
    for name in ("git", "pull_request", "release", "build", "deploy"):
        typer.echo(f"{name}:")
        if name == "git":
            typer.echo(f"  branch: {payload['branch']}")
            typer.echo(f"  dirty_files: {payload['dirty_files']}")
            upstream = payload["upstream"]
            typer.echo(f"  upstream: {upstream}")
        elif name == "pull_request":
            typer.echo(f"  {payload[name]}")
        elif name == "release":
            for key, value in payload[name].items():
                typer.echo(f"  {key}: {value}")
        elif name == "build":
            for image in payload[name]["images"]:
                typer.echo(f"  {image['registry']}/{image['name']}: {image['digest']}")
        else:
            for key, value in payload[name].items():
                typer.echo(f"  {key}: {value}")


def _print_plan(steps: list[dict[str, str]]) -> None:
    for step in steps:
        typer.echo(f"{step['step']}: {step['state']}")


@app.command()
def status(
    json_output: bool = typer.Option(False, "--json"),
    production: bool = typer.Option(False, "--production"),
) -> None:
    """Show read-only Git, PR, release, image, and deploy facts."""
    payload = _status_payload(Path.cwd(), production)
    if json_output:
        typer.echo(json.dumps(payload, sort_keys=True))
    else:
        _print_status(payload)
    status_check = payload["deploy"].get("status_check")
    if (
        production
        and status_check is not None
        and status_check.get("supported")
        and status_check.get("exit_status") != 0
    ):
        raise typer.Exit(code=1)


@app.command()
def plan(
    tag: str,
    json_output: bool = typer.Option(False, "--json"),
    production: bool = typer.Option(False, "--production"),
) -> None:
    """Show the ordered release-readiness checklist for TAG."""
    config = _config(Path.cwd())
    steps = _plan_states(Path.cwd(), tag, config, production)
    if json_output:
        typer.echo(json.dumps(steps, sort_keys=False))
    else:
        _print_plan(steps)
    if production and any(
        step["step"] == "deployed"
        and step["state"] not in ("done", "not_configured", "unsupported")
        for step in steps
    ):
        raise typer.Exit(code=1)


if __name__ == "__main__":
    app()
