#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = [
#   "typer>=0.12",
#   "httpx>=0.27",
# ]
# ///
"""Release cut for personal-site. Generated by project-kit.

Reads .project-kit/cliff.toml, drafts release notes via LiteLLM, tags + pushes,
creates GH release. Owned by this repo — edit freely.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

import httpx
import typer

PROJECT_NAME = "personal-site"
CLIFF_CONFIG = ".project-kit/cliff.toml"
BRANCH = "main"
LITELLM_MODEL = "deepseek-v4-pro-cloud"
# OpenAI-compatible base URL. Read from $LITELLM_BASE_URL at runtime, falling back
# to the value baked from .project-kit answers (public repos bake nothing here, so
# set the env var). release.py appends /chat/completions.
LITELLM_BASE_URL = os.environ.get("LITELLM_BASE_URL") or ""
INSTALL_COMMAND = None
# `just version` prod-version resolution (baked from .project-kit answers).
PROD_SOURCE = "none"
PROD_HOMELAB_ENV = ""

app = typer.Typer(add_completion=False)


def _run(cmd: list[str], **kw) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, check=True, capture_output=True, text=True, **kw)


def _current_branch() -> str:
    return _run(["git", "rev-parse", "--abbrev-ref", "HEAD"]).stdout.strip()


def _is_clean() -> bool:
    return _run(["git", "status", "--porcelain"]).stdout.strip() == ""


def _latest_tag() -> str | None:
    try:
        return _run(["git", "describe", "--tags", "--abbrev=0", "--match", "v*"]).stdout.strip()
    except subprocess.CalledProcessError:
        return None


def _next_version(level: str) -> str:
    last = _latest_tag() or "v0.0.0"
    m = re.match(r"v(\d+)\.(\d+)\.(\d+)", last)
    if not m:
        raise typer.Exit(code=1)
    major, minor, patch = map(int, m.groups())
    if level == "major":
        return f"v{major + 1}.0.0"
    if level == "minor":
        return f"v{major}.{minor + 1}.0"
    return f"v{major}.{minor}.{patch + 1}"


def _llm_api_key() -> str:
    """Resolve the LLM API key without baking it into the repo.

    Order: $LITELLM_API_KEY, $OPENAI_API_KEY, then the legacy
    ~/.config/litellm/config.json (api_key field) for backward compatibility.
    """
    for var in ("LITELLM_API_KEY", "OPENAI_API_KEY"):
        val = os.environ.get(var)
        if val:
            return val
    cfg_path = Path.home() / ".config" / "litellm" / "config.json"
    if cfg_path.is_file():
        try:
            return str(json.loads(cfg_path.read_text()).get("api_key", ""))
        except json.JSONDecodeError:
            return ""
    return ""


def _draft_notes(version: str, prev_tag: str | None) -> str:
    """Draft release notes via the configured LLM endpoint. Empty on failure."""
    base_url = LITELLM_BASE_URL.rstrip("/")
    api_key = _llm_api_key()
    try:
        rng = f"{prev_tag}..HEAD" if prev_tag else "HEAD"
        commits = _run(["git", "log", rng, "--pretty=format:- %h %s"]).stdout
        prompt = (
            f"Draft a short, editorial GitHub release narrative for {PROJECT_NAME} {version}.\n"
            f"Commits in this release:\n{commits}\n\n"
            f"{'Install: ' + INSTALL_COMMAND.replace('{version}', version.lstrip('v')) if INSTALL_COMMAND else ''}\n"
        )
        r = httpx.post(
            f"{base_url}/chat/completions",
            headers={"Authorization": f"Bearer {api_key}"} if api_key else {},
            json={"model": LITELLM_MODEL, "messages": [{"role": "user", "content": prompt}]},
            timeout=30,
        )
        r.raise_for_status()
        return str(r.json()["choices"][0]["message"]["content"])
    except (httpx.HTTPError, KeyError, json.JSONDecodeError) as exc:
        typer.echo(f"[warn] LiteLLM draft failed: {exc}", err=True)
        return ""


def preflight() -> None:
    typer.echo("[1/7] preflight…")
    if not _is_clean():
        typer.echo("error: working tree not clean", err=True)
        raise typer.Exit(code=1)
    branch = _current_branch()
    if branch != BRANCH:
        typer.echo(f"error: on branch {branch}, expected {BRANCH}", err=True)
        raise typer.Exit(code=1)
    if not Path(CLIFF_CONFIG).is_file():
        typer.echo(f"error: {CLIFF_CONFIG} missing", err=True)
        raise typer.Exit(code=1)
    typer.echo("       ok")


@app.command()
def cut(
    level: str = typer.Argument(..., help="patch | minor | major"),
    dry_run: bool = typer.Option(False, "--dry-run"),
    draft: bool = typer.Option(False, "--draft"),
) -> None:
    if level not in ("patch", "minor", "major"):
        typer.echo(f"error: bad level {level}", err=True)
        raise typer.Exit(code=1)
    if not dry_run:
        preflight()
    version = _next_version(level)
    typer.echo(f"[2/7] next version: {version}")
    if dry_run:
        typer.echo(f"[dry-run] would tag {version}, commit changelog, push, gh release create")
        return
    typer.echo("[3/7] regenerating CHANGELOG.md via git-cliff…")
    _run(["uvx", "git-cliff@latest", "--config", CLIFF_CONFIG, "--output", "CHANGELOG.md", "--tag", version])
    typer.echo("[4/7] drafting release notes via LiteLLM…")
    notes = _draft_notes(version, _latest_tag())
    typer.echo("[5/7] opening $EDITOR for review…")
    editor = os.environ.get("EDITOR", "vim")
    with tempfile.NamedTemporaryFile(mode="w", suffix=".md", delete=False) as f:
        f.write(notes)
        notes_path = f.name
    subprocess.run([editor, notes_path], check=False)
    # notes_path is reused below as --notes-file (the editor wrote in place).
    typer.echo("[6/7] commit + tag + push…")
    _run(["git", "add", "CHANGELOG.md"])
    _run(["git", "commit", "-m", f"chore(release): {version}"])
    _run(["git", "tag", "-a", version, "-m", f"release {version}"])
    _run(["git", "push", "origin", BRANCH, "--tags"])
    typer.echo(f"[7/7] gh release create {version}…")
    cmd = ["gh", "release", "create", version, "--notes-file", notes_path]
    if draft:
        cmd.append("--draft")
    _run(cmd)
    typer.echo(f"done. URL: $(gh release view {version} --json url -q .url)")


@app.command()
def version() -> None:
    """Print the local latest tag and the deployed prod version (per prod_source)."""
    typer.echo(f"local:  {_latest_tag() or '(none)'}")
    if PROD_SOURCE == "homelab" and PROD_HOMELAB_ENV:
        env_path = (
            Path(os.environ.get("HOME") or str(Path.home()))
            / "Documents" / "Homelab" / PROD_HOMELAB_ENV
        )
        label = f"~/Documents/Homelab/{PROD_HOMELAB_ENV} IMAGE_TAG"
        if not env_path.is_file():
            typer.echo(f"prod:   (file not found: {env_path})   [{label}]")
            return
        for raw in env_path.read_text().splitlines():
            line = raw.strip()
            if line.startswith("IMAGE_TAG="):
                val = line.split("=", 1)[1].strip().strip('"').strip("'")
                typer.echo(f"prod:   {val or '(empty)'}   [{label}]")
                return
        typer.echo(f"prod:   (IMAGE_TAG not set)   [{label}]")
    elif PROD_SOURCE == "none":
        typer.echo("prod:   (not configured — prod_source = none)")
    else:
        typer.echo(f"prod:   (prod_source={PROD_SOURCE!r} not supported by this generated release.py)")


@app.command()
def notes(tag: str = typer.Option(..., "--tag")) -> None:
    """Regenerate notes for an existing tag (no commit, no push)."""
    prev = _run(
        ["git", "describe", "--tags", "--abbrev=0", f"{tag}^", "--match", "v*"],
    ).stdout.strip() or None
    content = _draft_notes(tag, prev)
    sys.stdout.write(content)


if __name__ == "__main__":
    app()
